services:
    crmservice.local.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.4/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8888:80'
            - '${VITE_PORT:-5176}:${VITE_PORT:-5176}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: "debug"
            XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003 start_with_request=yes log=/var/log/php-fpm/xdebug.log"
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - redis
            - postgres
    postgres:
        image: 'postgres:16-alpine'
        ports:
            - '${FORWARD_DB_PORT:-5444}:5432'
        environment:
            POSTGRES_DB: '${DB_DATABASE:-app}'
            POSTGRES_USER: '${DB_USERNAME:-sail}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
        volumes:
            - 'sail-postgres:/var/lib/postgresql/data'
        networks:
            - sail
        healthcheck:
            test: "pg_isready -U ${DB_USERNAME:-sail}"
            interval: 10s
            timeout: 5s
            retries: 5
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6383}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1029}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8029}:8025'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-postgres:
        driver: local
    sail-redis:
        driver: local
